import { useState } from 'react';
import { useStore } from '../store/useStore';
import { DocumentStudio } from './DocumentStudio';
export const AdvancedReports = () => {
  const { projects,clients,timeEntries } = useStore();
  const [from,setFrom] = useState(''); const [to,setTo] = useState(''); const [clientId,setClientId] = useState(''); const [show,setShow] = useState(false);
  const invalid = Boolean(from && to && from>to);
  const selected = projects.filter(p=>(!from||p.contractStartDate.slice(0,10)>=from)&&(!to||p.contractStartDate.slice(0,10)<=to)&&(!clientId||p.clientId===clientId));
  const currencies = [...new Set(selected.map(p=>p.currency))];
  return <div className="space-y-6"><div className="section-heading"><div><p className="eyebrow">MFx / INTELLIGENCE</p><h1>Reports</h1><p>Real project values. No estimated growth or assumed payments.</p></div><button className="primary-button" disabled={invalid} onClick={()=>setShow(true)}>Generate Report</button></div><section className="panel form-columns"><label>Project start — from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Project start — to<input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.businessName}</option>)}</select></label><p>Payments are grouped by project start date, not by the date money was received.</p>{invalid&&<p role="alert">The end date must follow the start date.</p>}</section>{currencies.map(currency=>{const group=selected.filter(p=>p.currency===currency);return <section className="panel" key={currency}><div className="section-heading"><h2>{currency}</h2><span>{group.length} projects</span></div><div className="report-metrics">{[['Contract value',group.reduce((s,p)=>s+p.totalAmount,0)],['Collected',group.reduce((s,p)=>s+p.paidAmount,0)],['Outstanding',group.reduce((s,p)=>s+p.remainingAmount,0)]].map(([label,value])=><div key={label}><p>{label}</p><strong>{Number(value).toLocaleString()} <small>{currency}</small></strong></div>)}</div></section>})}<section className="panel"><h2>Project breakdown</h2><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Client / Reference</th><th>Value</th><th>Paid</th><th>Remaining</th></tr></thead><tbody>{selected.map(p=><tr key={p.id}><td>{clients.find(c=>c.id===p.clientId)?.businessName || 'Missing client'}<small>{p.refId}</small></td><td>{p.totalAmount.toLocaleString()} {p.currency}</td><td>{p.paidAmount.toLocaleString()} {p.currency}</td><td>{p.remainingAmount.toLocaleString()} {p.currency}</td></tr>)}</tbody></table>{!selected.length&&<p className="py-8">No projects in this period.</p>}</div></section>{show&&<DocumentStudio input={{kind:'report',projects:selected,clients,timeEntries,period:from||to?`${from||'…'} — ${to||'…'}`:undefined}} onClose={()=>setShow(false)}/>}</div>;
};
