import { useState } from 'react';
import { useStore } from '../store/useStore';
import { fetchGoogleSheetData, parseSheetRowToProject } from '../utils/googleSheets';
import type { SheetRow } from '../utils/googleSheets';
export function GoogleSheetsSync() {
 const [sheetId,setSheetId]=useState(''); const [apiKey,setApiKey]=useState(''); const [rows,setRows]=useState<SheetRow[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const preview=async()=>{setBusy(true);setRows([]);setMessage('');try{const found=await fetchGoogleSheetData(sheetId,apiKey);found.forEach(r=>parseSheetRowToProject(r,'preview'));setRows(found);setMessage(`${found.length} validated rows. Existing project references will be skipped to preserve local edits.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not read the sheet.');}finally{setBusy(false);}};
 const apply=()=>{let added=0;for(const row of rows){let state=useStore.getState();if(state.projects.some(p=>p.sourceRef===row.refId||p.refId===row.refId))continue;let client=state.clients.find(c=>c.businessName.trim().toLowerCase()===row.businessName.trim().toLowerCase());if(!client){client=state.createClient({businessName:row.businessName,contactPerson:row.contactPerson,phone:row.phone,color:'#0b58bd'});state=useStore.getState();}const parsed=parseSheetRowToProject(row,client.id);const {id:_legacyId,refId:_legacyRef,...projectData}=parsed;void _legacyId;void _legacyRef;state.createProject(projectData);added++;}setMessage(`Imported ${added} new projects. Skipped ${rows.length-added} existing source references.`);setRows([]);};
 const backup=()=>{const state=useStore.getState();const data={clients:state.clients,projects:state.projects,servicesCatalog:state.servicesCatalog,timeEntries:state.timeEntries,activeTimeEntry:state.activeTimeEntry};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mfx-workspace-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="panel space-y-4"><div className="section-heading"><div><h2>Google Sheets import</h2><p>Preview, then import new references. This is a one-way import.</p></div><button className="secondary-button" onClick={backup}>Download backup</button></div><div className="form-columns"><label>Sheet ID<input value={sheetId} onChange={e=>setSheetId(e.target.value.trim())}/></label><label>Read-only API key<input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)}/></label></div><p className="text-sm text-muted">Sheet1 columns A–P use the existing layout. Column Q is the actual paid amount; required for partial payments. Dates: YYYY-MM-DD. Imported currency: EGP. The key is kept only for this open session.</p><div className="flex gap-3"><button className="primary-button" disabled={busy||!sheetId||!apiKey} onClick={preview}>{busy?'Reading…':'Preview import'}</button>{rows.length>0&&<button className="primary-button" onClick={apply}>Import {rows.length} rows</button>}</div>{message&&<p role="status">{message}</p>}{rows.length>0&&<div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Reference</th><th>Client</th><th>Value (EGP)</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.refId}</td><td>{r.businessName}</td><td>{r.monthlyRate.toLocaleString()}</td></tr>)}</tbody></table></div>}</section>;
}
