import { useState } from 'react';
import { useDialog } from '../hooks/useDialog';
import { useStore } from '../store/useStore';
import type { Service } from '../types';
export function ServiceCatalog() {
  const {servicesCatalog,addServiceToCatalog,updateServiceInCatalog} = useStore();
  const [editing,setEditing] = useState<Service | null>(null);
  const [open,setOpen] = useState(false);
  return <section className="panel"><div className="section-heading"><div><h2>Service catalog</h2><p>Reusable services. Project prices remain independent.</p></div><button className="primary-button" onClick={()=>{setEditing(null);setOpen(true);}}>New Service</button></div><details className="catalog-details"><summary>Browse {servicesCatalog.length} services</summary><div className="catalog-grid">{servicesCatalog.map(service=><button className="catalog-item" key={service.id} onClick={()=>{setEditing(service);setOpen(true);}}><span>{service.name}</span><small dir="auto">{service.nameAr || 'Add Arabic wording'}</small><strong>{service.basePrice.toLocaleString()} <small>base price</small></strong></button>)}</div></details>{open&&<ServiceForm key={editing?.id || 'new'} service={editing} close={()=>setOpen(false)} save={s=>{if(editing) updateServiceInCatalog(s.id,s);else addServiceToCatalog(s);setOpen(false);}} />}</section>;
}
function ServiceForm({service,save,close}:{service:Service|null;save:(s:Service)=>void;close:()=>void}) {
  const [error,setError]=useState('');
  const dialogRef=useDialog(close);
  return <div ref={dialogRef} className="studio-overlay" role="dialog" aria-modal="true" aria-label="Service form"><form className="service-form panel" onSubmit={e=>{e.preventDefault();const d = new FormData(e.currentTarget);const name=String(d.get('name')).trim();const price=Number(d.get('price'));if(!name || !Number.isFinite(price)||price<0){setError('Enter a service name and a valid non-negative price.');return;}save({id:service?.id || crypto.randomUUID(),name,nameAr:String(d.get('nameAr')).trim(),description:String(d.get('description')).trim(),descriptionAr:String(d.get('descriptionAr')).trim(),subServices:String(d.get('deliverables')).split('\n').map(s=>s.trim()).filter(Boolean),subServicesAr:String(d.get('deliverablesAr')).split('\n').map(s=>s.trim()).filter(Boolean),basePrice:price,isRecurring:d.has('recurring'),isVariable:d.has('variable')});}}><div className="section-heading"><h2>{service?'Edit Service':'New Service'}</h2><button type="button" className="secondary-button" onClick={close}>Close</button></div>{error&&<p role="alert">{error}</p>}<div className="form-columns"><label>Service name (English)<input name="name" required defaultValue={service?.name}/></label><label>اسم الخدمة بالعربية<input name="nameAr" dir="rtl" defaultValue={service?.nameAr}/></label><label>Description (English)<textarea name="description" defaultValue={service?.description}/></label><label>الوصف بالعربية<textarea name="descriptionAr" dir="rtl" defaultValue={service?.descriptionAr}/></label><label>Deliverables — one per line<textarea name="deliverables" rows={4} defaultValue={service?.subServices?.join('\n')}/></label><label>المخرجات — بند في كل سطر<textarea name="deliverablesAr" dir="rtl" rows={4} defaultValue={service?.subServicesAr?.join('\n')}/></label></div><label>Base price (in the project's selected currency)<input name="price" type="number" min="0" step="0.01" required defaultValue={service?.basePrice ?? 0}/></label><div className="flex gap-5"><label><input name="recurring" type="checkbox" defaultChecked={service?.isRecurring}/> Recurring</label><label><input name="variable" type="checkbox" defaultChecked={service?.isVariable}/> Variable</label></div><button className="primary-button">Save Service</button></form></div>;
}
