import css from './reference.css?raw';
import logo from './logo';
import type { Client, Project, Service, TimeEntry } from '../types';
export type Language = 'en' | 'ar';
export type DocumentKind = 'invoice' | 'contract' | 'report';
export interface DocumentInput { kind: DocumentKind; language: Language; projects: Project[]; clients: Client[]; timeEntries?: TimeEntry[]; terms?: string; date?: string; period?: string }
export const escapeHTML = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const getDocumentReference = (kind: DocumentKind, clientRef?: string, date?: string) =>
  kind === 'report'
    ? `RPT-${(date || new Date().toISOString()).slice(0, 10)}`
    : `${kind === 'invoice' ? 'INV' : 'CON'}-${clientRef || 'MFx'}`;
const safeImage = (value?: string) => value && /^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(value) ? value : '';
export function generateDocument(input: DocumentInput) {
  const {kind, language, projects, clients} = input;
  const ar = language === 'ar';
  const t = (en:string, arabic:string) => ar ? arabic : en;
  const e = escapeHTML;
  const money = (n:number,c:string) => `${new Intl.NumberFormat(ar ? 'ar-EG' : 'en-GB', {maximumFractionDigits:2,minimumFractionDigits:2}).format(n)} ${e(c)}`;
  const date = (s?:string) => s && Number.isFinite(new Date(s).getTime()) ? new Date(s).toLocaleDateString(ar?'ar-EG':'en-GB') : '—';
  const title = kind === 'invoice' ? t('Invoice','فاتورة') : kind === 'contract' ? t('Service Agreement & Scope of Work','عقد خدمات ونطاق العمل') : t('Workspace Report','تقرير الأعمال');
  const project = projects[0];
  const client = clients.find(c=>c.id===project?.clientId);
  const ref = getDocumentReference(kind, client?.refId, input.date);
  const name = (s:Service) => ar ? s.nameAr || s.name : s.name;
  const serviceRows = (project?.services || []).map((s,i)=>`<tr class="service-row"><td class="service-cell"><div class="service-header"><div class="service-number">${String(i+1).padStart(2,'0')}</div><div class="service-name" dir="auto">${e(name(s))}</div>${s.isRecurring?`<span class="badge-tag badge-recurring">${t('Recurring','متكررة')}</span>`:''}${s.isVariable?`<span class="badge-tag badge-variable">${t('Variable','متغيرة')}</span>`:''}</div><ul class="sub-services-list">${[ar?s.descriptionAr || s.description:s.description,...(ar?s.subServicesAr?.length ? s.subServicesAr : s.subServices || []:s.subServices || [])].filter(Boolean).map(v=>`<li dir="auto">${e(v)}</li>`).join('')}</ul></td><td class="price-cell">${money(s.basePrice,project.currency)}</td></tr>`).join('');
  const meta = (label:string,value:string) => `<div class="meta-item"><span class="meta-label">${label}</span><span class="meta-val">${value}</span></div>`;
  const row = (label:string,value:string) => `<div class="calc-row"><span>${label}</span><strong>${value}</strong></div>`;
  let body = '';
  if(kind==='report') {
    const currencies = [...new Set(projects.map(p=>p.currency))];
    body = `<div class="section-title">${t('Financial summary','الملخص المالي')}</div><p class="context-note">${t('Values and recorded payments for projects starting in the selected period. This is not a payment transaction ledger.','قيم المشروعات والمدفوعات المسجلة للمشروعات التي بدأت خلال الفترة المحددة. هذا التقرير ليس سجل معاملات دفع.')}</p>`;
    for(const currency of currencies) {
      const group = projects.filter(p=>p.currency===currency);
      body += `<section class="summary-section"><div class="terms-block"><h4>${e(currency)}</h4><p>${group.length} ${t('projects','مشروعات')}</p></div><div class="totals-box">${row(t('Contract value','قيمة التعاقدات'),money(group.reduce((s,p)=>s+p.totalAmount,0),currency))}${row(t('Collected','المحصّل'),money(group.reduce((s,p)=>s+p.paidAmount,0),currency))}${row(t('Outstanding','المتبقي'),money(group.reduce((s,p)=>s+p.remainingAmount,0),currency))}</div></section>`;
    }
    body += `<table class="invoice-table report-table"><thead><tr>${[t('Project / Client','المشروع / العميل'),t('Value','القيمة'),t('Paid','المدفوع'),t('Remaining','المتبقي')].map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${projects.map(p=>`<tr><td class="service-cell"><strong>${e(p.refId)}</strong><p dir="auto">${e(clients.find(c=>c.id===p.clientId)?.businessName || t('Missing client','عميل غير موجود'))}</p></td><td>${money(p.totalAmount,p.currency)}</td><td>${money(p.paidAmount,p.currency)}</td><td>${money(p.remainingAmount,p.currency)}</td></tr>`).join('') || `<tr><td colspan="4">${t('No projects in this period.','لا توجد مشروعات في هذه الفترة.')}</td></tr>`}</tbody></table>`;
    const hours = (input.timeEntries || []).filter(entry=>projects.some(p=>p.id===entry.projectId)).reduce((sum,entry)=>sum+(entry.duration || 0),0)/3600000;
    body += `<div class="payment-schedule-box">${t('Completed tracked hours on these projects','ساعات العمل المسجلة المكتملة لهذه المشروعات')}: ${hours.toFixed(2)}</div>`;
  } else if(project && client) {
    body = `<div class="section-title">${t('Scope of Work & Service Distribution','نطاق العمل وتوزيع الخدمات')}</div><table class="invoice-table"><thead><tr><th>${t('Service Deliverables & Sub-Services','الخدمات والمخرجات التفصيلية')}</th><th>${t('Investment','القيمة')} (${project.currency})</th></tr></thead><tbody>${serviceRows}</tbody></table><section class="summary-section"><div class="terms-block"><h4>${t('Project details','تفاصيل المشروع')}</h4><p>${t('Project reference','رقم المشروع')}: ${e(project.refId)}<br>${t('Start date','تاريخ البداية')}: ${date(project.contractStartDate)}<br>${t('Deadline','موعد التسليم')}: ${date(project.deadline)}</p><div class="payment-schedule-box"><div class="payment-schedule-title">${t('Payment method','طريقة الدفع')}</div>${e(ar ? ({instapay:'إنستاباي','bank-transfer':'تحويل بنكي',cash:'نقدي',card:'بطاقة'}[project.paymentMethod]) : project.paymentMethod)}${project.dueMethod?`<p dir="auto">${e(project.dueMethod)}</p>`:''}</div></div><div class="totals-box">${row(t('Total service value','إجمالي قيمة الخدمات'),money(project.totalAmount,project.currency))}${row(t('Amount paid','المبلغ المدفوع'),money(project.paidAmount,project.currency))}<div class="grand-total-card"><strong>${t('Balance due','المبلغ المتبقي')}</strong><strong>${money(project.remainingAmount,project.currency)}</strong></div></div></section>${project.notes?`<section class="notes-section"><h4>${t('Project notes','ملاحظات المشروع')}</h4><p dir="auto">${e(project.notes)}</p></section>`:''}`;
    if(kind==='contract') body += `<section class="notes-section"><div class="section-title">${t('Agreement terms','بنود الاتفاق')}</div><p class="preserve-lines" dir="auto">${e(input.terms?.trim() || t('Draft — add and review the agreement terms before signing.','مسودة — أضف بنود الاتفاق وراجعها قبل التوقيع.'))}</p></section><div class="signatures"><div>${t('For MFx Digital Solutions','عن MFx Digital Solutions')}<div class="signature-line"></div>${t('Signature / Date','التوقيع / التاريخ')}</div><div>${e(client.businessName)}<div class="signature-line"></div>${t('Signature / Date','التوقيع / التاريخ')}</div></div>`;
  }
  const extra = `html{color-scheme:light}.meta-val{white-space:normal;overflow-wrap:anywhere}.header{flex-wrap:wrap}.invoice-table{table-layout:fixed}.invoice-table th:last-child{width:25%}.invoice-table td{overflow-wrap:anywhere}.price-cell{white-space:normal}.service-header{flex-wrap:wrap}.context-note{font-size:11px;color:var(--slate);margin:0 0 16px}.summary-section{margin:14px 0;break-inside:avoid}.notes-section{margin-top:18px;font-size:12px;color:var(--slate);white-space:pre-wrap;overflow-wrap:anywhere}.signatures{display:flex;justify-content:space-between;gap:30px;font-size:12px;margin:36px 0 16px;break-inside:avoid}.signatures>div{width:45%}.signature-line{border-bottom:1px solid var(--border);height:40px;margin-bottom:8px}.footer{padding:16px 28px;border-top:1px solid var(--border);font-size:10px;color:var(--slate);display:flex;justify-content:space-between}.report-table th:last-child{width:auto}.report-table td{padding:10px;font-size:11px}.report-table th:first-child{width:34%}.preserve-lines{white-space:pre-wrap}.client-side{max-width:100%;font-size:12px}.document-title{font-size:19px;font-weight:800;padding:18px 28px 0;color:var(--primary)}[dir=rtl] .vendor-info{border-left:0;border-right:2px solid var(--border);padding-left:0;padding-right:12px}[dir=rtl] .sub-services-list{padding-left:0;padding-right:28px}[dir=rtl] .sub-services-list li:before{left:auto;right:-12px}[dir=rtl] .invoice-table th,[dir=rtl] .invoice-table td{text-align:right}[dir=rtl] .payment-schedule-box{border-left:1px solid #cbd5e1;border-right:3.5px solid var(--primary)}@page{size:A4;margin:8mm 6mm}@media print{html,body{background:white!important;padding:0!important}.proposal-container{width:100%!important;max-width:none!important;border:0!important;box-shadow:none!important;overflow:visible!important}.top-bar,.grand-total-card{print-color-adjust:exact;-webkit-print-color-adjust:exact}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}thead{display:table-header-group}tr{break-inside:avoid}h4,.section-title{break-after:avoid}.header{break-inside:avoid}.content{padding:18px 14px}.summary-section{display:flex}.totals-box{width:260px}.proposal-meta{grid-template-columns:repeat(4,1fr)}}`;
  return `<!DOCTYPE html><html lang="${language}" dir="${ar?'rtl':'ltr'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)} · ${e(ref)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"><style>${css}\n${extra}</style></head><body><div class="proposal-container"><div class="top-bar"></div><header class="header"><div class="vendor-side"><img src="${logo}" class="vendor-logo-img" alt="MFx"><div class="vendor-info"><h1>MFx <span>Digital Solutions</span></h1><p>www.mfx360.com</p></div></div><div class="client-side">${safeImage(client?.logoUrl)&&kind!=='report'?`<img src="${safeImage(client?.logoUrl)}" class="client-logo-item" alt="">`:''}<strong dir="auto">${kind==='report'?t('Business overview','نظرة عامة على الأعمال'):e(client?.businessName)}</strong></div></header><div class="document-title">${title}</div><div class="proposal-meta">${meta(t('Document reference','رقم المستند'),e(ref))}${meta(t('Issue date','تاريخ الإصدار'),date(input.date || new Date().toISOString()))}${meta(t('Client account','حساب العميل'),kind==='report'?t('All selected clients','العملاء المحددون'):e(client?.refId))}${meta(kind==='report'?t('Period','الفترة'):t('Billing structure','نظام التعاقد'),kind==='report'?e(input.period || t('All dates','كل التواريخ')):e(ar?({fixed:'قيمة ثابتة',monthly:'شهري',hourly:'بالساعة',retainer:'تعاقد دوري'}[project?.billingModel || 'fixed']):project?.billingModel))}</div><main class="content">${body}</main><footer class="footer"><span>MFx Digital Solutions</span><span>${e(ref)}</span></footer></div></body></html>`;
}
